name: Dataflow

on:
  push:
    paths:
      - dataflow/**
      - .github/workflows/dataflow.yaml
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

defaults:
  run:
    working-directory: dataflow

env:
  CONTAINER_IMAGE: us-docker.pkg.dev/mimo-capital-1/docker-1/mimo-capital-cryptio/container:${{ github.ref_name }}
  TEMPLATE_IMAGE: us-docker.pkg.dev/mimo-capital-1/docker-1/mimo-capital-cryptio/template:${{ github.ref_name }}
  TEMPLATE_METADATA: gs://mimo-capital-cryptio/dataflow/template-${{ github.ref_name }}.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          file: ./dataflow/Dockerfile.container
          context: ./dataflow
          tags: ${{ env.CONTAINER_IMAGE }}
          push: true
          build-args: |
            GH_REF=${{ github.ref_name }}

      - uses: docker/build-push-action@v4
        with:
          file: ./dataflow/Dockerfile.template
          context: ./dataflow
          tags: ${{ env.TEMPLATE_IMAGE }}
          push: true
          build-args: |
            GH_REF=${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: >-
          gcloud dataflow flex-template build ${{ env.TEMPLATE_METADATA }} \
            --image=${{ env.TEMPLATE_IMAGE }} \
            --sdk-language=PYTHON \
            --metadata-file=metadata.json
